### ISSUE TITLE
An unexpected error occurred.

### ISSUE THREAD

**Issue by iambenmitchell** [AndreVasilev/AVVPNService#1]
Hello, I am trying to make a basic app for connecting to my IKEV2 server. I imported the framework and made a button like so:

```
Button(action: {
                // Connect
                AVVPNService.shared.connect(credentials:.IKEv2(server: "server.address", username: "username", password: "password", remoteId: "server.address", localId: "username")) { error in
                print(error)
                }
            })
```

However, when I press the button, it asks me to allow the vpn, so I do so. But it does not connect. I tried pressing connect again but it fails.

Going into settings and manually toggling also doesn't work, I says connecting then quickly switches to off and give the error "An unexpected error occurred."

In the Xcode console, this is what happens:

```
2020-07-22 15:34:13.605643+0100 Guard[3720:863633] libMobileGestalt MobileGestaltCache.c:166: Cache loaded with 4563 pre-cached in CacheData and 52 items in CacheExtra.
genpnil
genpnil
```

If it helps, I am using this as the server: [Server](https://github.com/jawj/IKEv2-setup)

Thanks :)

I also opened an issue on the server's GitHub since I think it is to do with the config.[Github]( https://github.com/jawj/IKEv2-setup/issues/108)

**Comment by AndreVasilev** [comment]
Hello!

Thank you for your interest, but I'm afraid that the problem is not in my framework.
PLease, look to the answer to your issue on the server's GitHub

**Comment by iambenmitchell** [comment]
> Hello!
> 
> Thank you for your interest, but I'm afraid that the problem is not in my framework.
> PLease, look to the answer to your issue on the server's GitHub

Yes, how do I go about using other cyphers with YOUR framework?

**Comment by AndreVasilev** [comment]
Sorry for the long answer.
This framework was made as a helper for using vpn services in my own app.
You can make a fork and implement handling other cyphers by your own :)
