### ISSUE TITLE
How to observe in Swift 5.9 with swiftui

### ISSUE THREAD

**Issue by Erwin1989** [AndreVasilev/AVVPNService#4]
I can't set the delegate in Swiftui. 

Can you share a example on how to do it (my experience with swift is limit but I managed to get the VPN connecting/disconnect, etc.).

Thank you!

**Comment by AndreVasilev** [comment]
Hello Erwin1989!

You're right, this project is a bit outdated. But I'm not going to maintain this project now, maybe sometime in the future.

Sorry :(

**Comment by Erwin1989** [comment]
Thank you for the fast response.
